# config.yaml

# AI Clients
clients:
  # Llama2 model running on Ollama
  - model: llama2
    type: ollama

  # OpenAI GPT 3.5 Turbo Instruct model
  - model: gpt-3.5-turbo-instruct
    type: openai
    max_tokens: 100
    temperature: 0.0
    system_prompt: You are ChatGPT, an AI assistant.
    disabled: true

  # OpenAI GPT 4o mini model
  - model: gpt-4o-mini
    type: openai
    max_tokens: 100
    temperature: 0.0
    system_prompt: You are ChatGPT, an AI assistant.
    disabled: true

  # Anthropic Claude 3 Haiko model
  - model: claude-3-haiku-20240307
    type: anthropic
    max_tokens: 1000
    temperature: 0
    system_prompt: You are Claude 3 Haiku, an AI assistant.
    disabled: true

  # Amazon Bedrock - Mistral 7B model
  - model: mistral.mistral-7b-instruct-v0:2
    type: bedrock
    max_tokens: 500
    temperature: 0.7
    top_p: 0.95
    disabled: true

  # Hugging Face GPT-2 model
  - model: gpt2
    type: huggingface
    max_tokens: 100
    temperature: 0.7
    tokenizer: gpt2
    device: cpu       # Use 'cuda' for GPU
    system_prompt: You are a helpful AI assistant.
    disabled: true


# Define your Test Cases here...
test_cases:
  - name: "Capital of Malaysia"
    prompt: "What is the capital of Malaysia?"
    expected:
      - type: substring
        case_sensitive: true      # Case-sensitive matching
        values: Kuala Lumpur
  - name: "Water Cycle Summary"
    prompt: "Summarize the importance of the water cycle."
    expected:
      - type: word
        match_all: true           # Match all values
        values:
          - "evaporation"
          - "condensation"
          - "precipitation"
  - name: "Translate to Italian"
    prompt: 'Translate the following English text to Italian: "Good morning."'
    expected:
      - type: word
        case_sensitive: true
        values: "Buongiorno"
  - name: "Chicken Joke"
    prompt: "Tell me a joke about chickens."
    expected:
      - type: substring
        values: "chicken"
    forbidden:
      - type: substring
        values:
          - "inappropriate"
          - "offensive"
  - name: "Strawberry test"
    prompt: "How many Rs are there in the word strawberry"
    expected:
      - type: word
        values:
          - three
          - "3"
    forbidden:
      - type: word
        values:
          - two
          - "2"
